// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoadedImageData = { filePath: string, base64Data: string, width: number, height: number, };
